project:
  title: "funathon-streamlit"
  render:
    - "index.qmd"

format:
    html:
        toc: true
        code-fold: true
        code-summary: "Dérouler la solution 🟡"
        code-tools: true

output: true
