apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: funathon2023_sujet4
spec:
  project: default
  source:
    repoURL: https://github.com/InseeFrLab/funathon2023_sujet4.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-formation
  syncPolicy:
    automated:
      selfHeal: true
